project:
  type: website
  output-dir: docs

render:
  - index.qmd

website:
  title: "Statistics"
  reader-mode: true


format:
  html:
    theme:
      light: flatly
      dark: darkly
      
    

